# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pentagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='NULL', upload_to=''),
        ),
    ]
