# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pentagram', '0007_remove_likes_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set([('photo', 'user')]),
        ),
    ]
